model: ./models/models--Qwen--Qwen3-4B-Instruct-2507/snapshots/cdbee75f17c01a7cc42f958dc650907174af0554
served_model_name:
  - qwen3-4b-instruct
host: 0.0.0.0
port: 9000
max_model_len: 16384
gpu_memory_utilization: 0.85
max_num_batched_tokens: 2048
enable_chunked_prefill: true